= Error match
:sectnums:
:sectnumlevels: 5
:toc: left
:toclevels: 5
:source-highlighter: rouge
:icons: font

This package was created to enable an easier way to match errors in Go.

It provides 2 ways to work with matching Go errors:

* link:https://github.com/tompaz3/fungo/tree/main/match/error[] - with simple free functions to work with errors
* link:https://github.com/tompaz3/fungo/tree/main/match/error/patternmatch[] [experimental] - with `Switch` - `Case` matching helpers and rules.

[#error_package]
== error
This packages provides a set of functions to match Go errors.

* `func ErrorType[E error](err error) (E, bool)` - to match an error by type.
* `func ErrorTypeMatches[E error](err error, prod ErrorPredicate[E]) (E, bool)` - to match an error by type and predicate (type assertion is applied first).
* `func ErrorMatches(err error, pred ErrorPredicate[error])(error, bool)` - to match an error by any predicate.

Additionally, `ErrorPredicate` type allows composition of predicates using `And` and `Or` functions.

[#error_package-examples]
=== Examples

For all the examples below, we will use the following error types.
For the sake of brevity, we won't be showing the `Error` interface implementation, but let's assume that all the errors below have the `Error() string` function implemented.
See the full implementation at link:https://github.com/tompaz3/fungo/blob/main/match/error/example_errors_test.go[example_errors_test.go]

[source,go,linenums,caption="errors.go"]
----
type InsufficientFundsError struct {
	AccountID string
	Amount    float64
}

type ProductNotFoundError struct {
	ProductID string
}

type UnsupportedCurrencyError struct {
	Currency string
}

type PaymentGatewayRejectedError struct {
	ReasonCode    string
	ReasonMessage string
}
----

==== Match errors by type

See full example at link:https://github.com/tompaz3/fungo/blob/main/match/error/examples_test.go#L53[examples_test.go#HandleErrorByType]

[source,go,linenums,caption="type_check.go"]
----
func HandleErrorByType(recErr error) Response {
	if err, ok := match.ErrorType[ProductNotFoundError](recErr); ok {
		return Response{
			StatusCode:   http.StatusBadRequest,
			ErrorCode:    ErrorCodeProductNotFound,
			ErrorMessage: fmt.Sprintf("product with id %q not found", err.ProductID),
		}
	}
	if err, ok := match.ErrorType[UnsupportedCurrencyError](recErr); ok {
		return Response{
			StatusCode:   http.StatusBadRequest,
			ErrorCode:    ErrorCodeUnsupportedCurrency,
			ErrorMessage: fmt.Sprintf("unuspported currency %q", err.Currency),
		}
	}
	if err, ok := match.ErrorType[InsufficientFundsError](recErr); ok {
		fmt.Println(err.Error())
		return Response{
			StatusCode:   http.StatusInternalServerError,
			ErrorCode:    ErrorPaymentError,
			ErrorMessage: "payment error",
		}
	}
	if err, ok := match.ErrorType[PaymentGatewayRejectedError](recErr); ok {
		return Response{
			StatusCode: http.StatusInternalServerError,
			ErrorCode:  ErrorPaymentError,
			ErrorMessage: fmt.Sprintf(
				"payment gateway rejected with code %q and message %q",
				err.ReasonCode,
				err.ReasonMessage,
			),
		}
	}

	return Response{
		StatusCode:   http.StatusInternalServerError,
		ErrorCode:    ErrorCodeUnexpectedError,
		ErrorMessage: "unexpected error occurred",
	}
}
----
